#cloud-config
version: v1
bootcmd:
  - sed -i '/cloud-init/d' /etc/apk/world
  - sed -i '/openssh/d' /etc/apk/world
  - sed -i '/py3-netifaces/d' /etc/apk/world
  - sed -i '/py3-pyserial/d' /etc/apk/world
packages:
        - alpine-sdk
        - openssh-client
        - less
        - ncdu
        - vim
packages_update: true
packages_upgrade: true
users:
  - default
  - name: alpine
    gecos: Alpine User
    primary_group: alpine
    groups: wheel, abuild
    lock_passwd: false
